module.exports = [
  'Academic',
  'Admired Icon',
  'Angling Ace',
  'Archaeology Scholar',
  'Artistic Prodigy',
  'Athlete',
  'Beach Life',
  'Bestselling Author',
  'Big Happy Family ',
  'Bodybuilder',
  'Championship Rider',
  'Chef',
  'Chief of Mischief ',
  'City Native',
  'Computer Whiz',
  'Country Caretaker',
  'Creative Genius',
  'Cure Seeker',
  'Drama Llama',
  'Eco Innovator',
  'Emissary of the Collective',
  'Enforcer of Order ',
  'Expert Nectar Maker',
  'Extreme Sports Enthusiast',
  'Fabulously Filthy',
  'Fabulously Wealthy',
  'Freelance Botanist',
  'Friend of the Animals',
  'Friend of the World',
  'Galactic Privateer',
  'Goal Oriented ',
  'Good Vampire',
  'Hope VS Order',
  'Inner Peace',
  'Joke Star ',
  'Jungle Explorer',
  'Leader of the Pack',
  'Live Fast ',
  'Lone Wolf ',
  'Lord/Lady of the Knits',
  'Mansion Baron',
  'Master Actor/Master Actress',
  'Master Chef',
  'Master Maker',
  'Master Mixologist ',
  'Master Vampire',
  'Mind and Body',
  'Mt. Komorebi Sightseer',
  'Musical Genius',
  'Neighborhood Confidante',
  'Nerd Brain',
  'Outdoor Enthusiast',
  'Painter',
  'Painter Extraordinaire',
  'Paragon of Hope ',
  'Party Animal',
  'Perfectly Pristine ',
  'Playtime Captain',
  'Public Enemy',
  'Purveyor of Potions',
  'Rambunctious Scamp',
  'Renaissance Sim ',
  'Self-Care Specialist',
  'Serial Romantic',
  'Slumber Party Animal',
  'Social Butterfly',
  'Soulmate',
  'Spellcraft & Sorcery',
  'StrangerVille Mystery',
  'Successful Lineage',
  'Super Parent',
  'The Curator',
  'The Positivity Challenge',
  'Trend-Setter',
  'Vampire Family',
  'Villainous Valentine',
  'Werewolf Initiate',
  'Whiz Kid ',
  'Wildfang Renegade',
  'World-Famous Celebrity',
  'Zen Guru'
]
