module.exports = [
  'Academic',
  'Angling Ace',
  'Archaeology Scholar',
  'Artistic Prodigy',
  'Beach Life',
  'Bestselling Author',
  'Big Happy Family',
  'Bodybuilder',
  'Chief of Mischief',
  'City Native',
  'Computer Whiz',
  'Eco Innovator',
  'Extreme Sports Enthusiast',
  'Fabulously Wealthy',
  'Freelance Botanist',
  'Friend of the Animals',
  'Friend of the World',
  'Good Vampire',
  'Grilled Cheese',
  'Joke Star',
  'Jungle Explorer',
  'Leader of the Pack',
  'Lord/Lady of the Knits',
  'Mansion Baron',
  'Master Actor/Master Actress',
  'Master Chef',
  'Master Maker',
  'Master Mixologist',
  'Master Vampire',
  'Mt. Komorebi Sightseer',
  'Musical Genius',
  'Nerd Brain',
  'Outdoor Enthusiast',
  'Painter Extraordinaire',
  'Party Animal',
  'Public Enemy',
  'Purveyor of Potions',
  'Rambunctious Scamp',
  'Renaissance Sim',
  'Serial Romantic',
  'Social Butterfly',
  'Soulmate',
  'Spellcraft & Sorcery',
  'StrangerVille Mystery',
  'Successful Lineage',
  'Super Parent',
  'The Curator',
  'The Positivity Challenge',
  'Vampire Family',
  'Whiz Kid',
  'World-Famous Celebrity'
]
