module.exports = [
  'A Gift of Credits',
  'A True Master',
  'Active',
  'Adventurous',
  'Affectionate',
  'Afizzionado',
  'Aggressive',
  'Alluring',
  'Aloof',
  'Always Welcome',
  'Ambitious',
  'Ancient Bloodline',
  'Angelic',
  'Angler\'s Tranquility',
  'Animal Affection',
  'Animal Enthusiast',
  'Animal Whisperer',
  'Antiseptic',
  'Appraiser',
  'Argumentative',
  'Art Lover',
  'Bad Manners',
  'Beguiling',
  'Beloved',
  'Bookworm',
  'Brave',
  'Bro',
  'Business Savvy',
  'Calm',
  'Calming Aura',
  'Capable Mountaineer',
  'Career-Minded',
  'Carefree',
  'Cat Lover',
  'Cautious',
  'Champion Genes',
  'Champion of the People',
  'Champion',
  'Charismatic Crooner',
  'Charmer',
  'Cheerful',
  'Child of the Islands',
  'Child of the Ocean',
  'Childish',
  'Chomp Champion',
  'Chopstick Savvy',
  'Clear Perspective',
  'Clever',
  'Clingy',
  'Clumsy',
  'Cold Acclimation',
  'Collector',
  'Companion',
  'Compassionate',
  'Confidante',
  'Connections',
  'Consumed By the Mother',
  'Couch Potato',
  'Creative Visionary',
  'Creative',
  'Creatively Gifted',
  'Critically Connected',
  'Curious',
  'Dance Machine',
  'Dastardly',
  'Dauntless',
  'Death by Anger',
  'Death by Beetles',
  'Death By Being Crushed By a Murphy Bed',
  'Death By Being Swarmed By Flies',
  'Death by Cowplant',
  'Death by Drowning',
  'Death by Electrocution',
  'Death by Embarrassment',
  'Death by Falling from Heights',
  'Death by Fire',
  'Death by Flowers',
  'Death by Freezing',
  'Death by Hunger',
  'Death by Killer Chicken',
  'Death by Killer Rabbit',
  'Death by Laughter',
  'Death by Lightning',
  'Death by Meteorite',
  'Death by Old Age',
  'Death by Overexertion',
  'Death by Overheating',
  'Death by Poison',
  'Death by Pufferfish',
  'Death by Rabid Rodent Fever',
  'Death by Spellcaster Overload',
  'Death by Steam',
  'Death by Stink Capsule',
  'Death by Sunlight',
  'Death by Urban Myth',
  'Death by Vending Machine',
  'Defiant',
  'Distant',
  'Dog Lover',
  'Domestic',
  'Dormant Wolf',
  'Eco Master',
  'Eco-Engineer',
  'Emotional Control',
  'Energetic',
  'Entrepreneur',
  'Entrepreneurial',
  'Erratic',
  'Essence of Flavor',
  'Evil',
  'Expert Mountaineer',
  'Expressionistic',
  'Family-oriented',
  'Fast & Fastidious',
  'Father Winter\'s Baby',
  'Fearful',
  'Fertile',
  'Filth Dweller',
  'Fluffy',
  'Foodie',
  'Forever Fresh',
  'Forever Full',
  'Free Services',
  'Free Spirit',
  'Freegan',
  'Fresh Chef',
  'Friend of the Moonwood Collective',
  'Friend of the Wildfangs',
  'Friendly',
  'Frisky',
  'Frugal',
  'Fussy',
  'Geek',
  'Genius',
  'Ghastly Consequences',
  'Gloomy',
  'Glutton',
  'Good Manners',
  'Good',
  'Goofball',
  'Great Kisser',
  'Great Storyteller',
  'Greater Wolf Blood',
  'Green Fiend',
  'Gregarious',
  'Gym Rat',
  'Hairy',
  'Handy',
  'Happy Infant',
  'Happy Toddler',
  'Hardly Hungry',
  'Hates Children',
  'Headstrong',
  'Heat Acclimation',
  'Heatproof',
  'Hero of StrangerVille',
  'Heroic Presence',
  'High Confidence',
  'High Maintenance',
  'High Metabolism',
  'High Self-Esteem',
  'Higher Education',
  'Highflier',
  'Hilarious',
  'Home Turf',
  'Horse Lover',
  'Hot-Headed',
  'Hunter',
  'I am the Master',
  'I\'m a Bear!',
  'Ice Proof',
  'Iconic',
  'Idea Person',
  'Immortal',
  'In the Know',
  'Incredibly Friendly',
  'Independent',
  'Infected',
  'Influential Individual',
  'Inquisitive',
  'Insensitive',
  'Insider',
  'Inspired Explorer',
  'Intelligent',
  'Intense',
  'Irresponsible',
  'Jealous',
  'Jumpy',
  'Kindness Ambassador',
  'Kleptomaniac',
  'Lactose Intolerant',
  'Laid-Back',
  'Lazy',
  'Legendary Stamina',
  'Loner',
  'Long Lived',
  'Loud',
  'Loves Outdoors',
  'Low Confidence',
  'Low Self-Esteem',
  'Loyal',
  'Lunar Confidant',
  'Lunar Link',
  'Maker',
  'Marketable',
  'Master Crafter',
  'Master Mixer',
  'Master of the Sea',
  'Mastermind',
  'Materialistic',
  'Matriarch/Patriarch',
  'Mean Streak',
  'Mean',
  'Mediator',
  'Mellow',
  'Melt Master',
  'Memorable',
  'Mental Magister',
  'Mentally Gifted',
  'Mentor',
  'Middling Mountaineer',
  'Mischievous',
  'Morning Sim',
  'Muse of the Maker',
  'Muser',
  'Museum Patron',
  'Music Lover',
  'Mystical Sensing',
  'Natural Leader',
  'Natural Speaker',
  'Naturalist',
  'Nature Conversationalist',
  'Neat',
  'Needs No One',
  'Needy',
  'Neutral Confidence',
  'Never Weary',
  'Night Owl',
  'Night Wraith',
  'Noncommittal',
  'Observant',
  'Outgoing',
  'Over-Achiever',
  'Overachiever',
  'Pack Animal',
  'Paranoid',
  'Paranormal Investigator',
  'Party Animal',
  'Perfect Host',
  'Perfectionist',
  'Physically Gifted',
  'Picky Eater',
  'Piper',
  'Player',
  'Playful',
  'Poetic',
  'Potion Master',
  'Practiced Host',
  'Prepared Voyager',
  'Professional Slacker',
  'Professorial',
  'Proper',
  'Prowler',
  'Quick Learner',
  'Rancher',
  'Rebellious',
  'Recycle Disciple',
  'Refined Lupine',
  'Regained Humanity',
  'Relatable',
  'Responsible',
  'Role Model',
  'Romantic',
  'Sacred Knitting Knowledge',
  'Savant',
  'Scouting Aptitude',
  'Seasoned Gamer',
  'Seldom Sleepy',
  'Self-Absorbed',
  'Self-Assured',
  'Self-Care Expertise',
  'Sensitive',
  'Shameless',
  'Shrewd',
  'Sickness Resistance',
  'Silly',
  'Sincere',
  'Skittish',
  'Sleight of Hand',
  'Sleuth',
  'Slinger of Spells',
  'Slob',
  'Smart',
  'Snob',
  'Socially Awkward',
  'Socially Gifted',
  'Spa Membership',
  'Spectral Look',
  'Speed Cleaner',
  'Speed Reader',
  'Spice Hound',
  'Spoiled',
  'Squeamish',
  'Steel Bladder',
  'Storm Chaser',
  'Stoves and Grills Master',
  'Strong Bloodline',
  'Stubborn',
  'Sulani Mana',
  'Sunny',
  'Super Green Thumb',
  'Supreme Authority',
  'Survival Instinct',
  'Survivalist',
  'Talkative',
  'Temporary Genius',
  'Territorial',
  'Threatening Presence',
  'Thrifty',
  'Top Notch Infant',
  'Top-Notch Toddler',
  'Tormentor',
  'Treasure Hunter',
  'Troublemaker',
  'Twisted Heart',
  'Uncontrolled Emotions',
  'Unflirty',
  'Unhappy Infant',
  'Unstoppable Fame',
  'Untroubled',
  'Vegetarian',
  'Vicarious',
  'Vocal',
  'Waterproof',
  'Weak Bloodline',
  'Webmaster',
  'Well-Mannered Foal',
  'Werewolf Ally',
  'Wiggly',
  'Wild',
  'World-Renowned Actor',
  'Worldly Knowledge'
]
