module.exports = [
  'A True Master',
  'Active',
  'Adventurous',
  'Affectionate',
  'Afizzionado',
  'Aggressive',
  'Alluring',
  'Aloof',
  'Always Welcome',
  'Ambitious',
  'Ancient Bloodline',
  'Angelic',
  'Angler\'s Tranquility',
  'Animal Affection',
  'Animal Whisperer',
  'Antiseptic',
  'Appraiser',
  'Argumentative',
  'Art Lover',
  'Bad Manners',
  'Beguiling',
  'Beloved',
  'Bookworm',
  'Bro',
  'Business Savvy',
  'Capable Mountaineer',
  'Career-Minded',
  'Carefree',
  'Cat Lover',
  'Champion of the People',
  'Charismatic Crooner',
  'Charmer',
  'Cheerful',
  'Child of the Islands',
  'Child of the Ocean',
  'Childish',
  'Chopstick Savvy',
  'Clever',
  'Clingy',
  'Clumsy',
  'Cold Acclimation',
  'Collector',
  'Companion',
  'Compassionate',
  'Connections',
  'Consumed By the Mother',
  'Couch Potato',
  'Creative Visionary',
  'Creative',
  'Creatively Gifted',
  'Critically Connected',
  'Curious',
  'Dance Machine',
  'Dastardly',
  'Death By Being Crushed By a Murphy Bed',
  'Death By Being Swarmed By Flies',
  'Death by Anger',
  'Death by Beetles',
  'Death by Cowplant',
  'Death by Drowning',
  'Death by Electrocution',
  'Death by Embarrassment',
  'Death by Falling from Heights',
  'Death by Fire',
  'Death by Flowers',
  'Death by Freezing',
  'Death by Hunger',
  'Death by Laughter',
  'Death by Lightning',
  'Death by Old Age',
  'Death by Overexertion',
  'Death by Overheating',
  'Death by Poison',
  'Death by Pufferfish',
  'Death by Rabid Rodent Fever',
  'Death by Spellcaster Overload',
  'Death by Steam',
  'Death by Sunlight',
  'Death by Vending Machine',
  'Distant',
  'Dog Lover',
  'Domestic',
  'Eco Master',
  'Eco-Engineer',
  'Emotional Control',
  'Entrepreneur',
  'Entrepreneurial',
  'Erratic',
  'Essence of Flavor',
  'Evil',
  'Expert Mountaineer',
  'Expressionistic',
  'Family-Oriented',
  'Fast & Fastidious',
  'Father Winter\'s Baby',
  'Fertile',
  'Filth Dweller',
  'Fluffy',
  'Foodie',
  'Forever Fresh',
  'Forever Full',
  'Free Services',
  'Free Spirit',
  'Freegan',
  'Fresh Chef',
  'Friendly',
  'Frisky',
  'Frugal',
  'Fussy',
  'Geek',
  'Genius',
  'Ghostly Consequences',
  'Gloomy',
  'Glutton',
  'Good Manners',
  'Good',
  'Goofball',
  'Great Kisser',
  'Great Storyteller',
  'Green Fiend',
  'Gregarious',
  'Gym Rat',
  'Hairy',
  'Handy',
  'Happy Toddler',
  'Hardly Hungry',
  'Hates Children',
  'Heat Acclimation',
  'Heatproof',
  'Hero of StrangerVille',
  'Heroic Presence',
  'High Metabolism',
  'Higher Education',
  'Hilarious',
  'Home Turf',
  'Hot-Headed',
  'Hunter',
  'I am the Master',
  'I\'m a Bear!',
  'Ice Proof',
  'Immortal',
  'In the Know',
  'Incredibly Friendly',
  'Independent',
  'Infected',
  'Influential Individual',
  'Inquisitive',
  'Insane',
  'Insensitive',
  'Insider',
  'Irresponsible',
  'Jealous',
  'Jumpy',
  'Kindness Ambassador',
  'Kleptomaniac',
  'Laid-Back',
  'Lazy',
  'Legendary Stamina',
  'Loner',
  'Long Lived',
  'Loud',
  'Loves Outdoors',
  'Loyal',
  'Maker',
  'Marketable',
  'Master Crafter',
  'Master Mixer',
  'Master of the Sea',
  'Mastermind',
  'Materialistic',
  'Matriarch/Patriarch',
  'Mean Streak',
  'Mean',
  'Mediator',
  'Melt Master',
  'Memorable',
  'Mentally Gifted',
  'Mentor',
  'Middling Mountaineer',
  'Mischievous',
  'Morning Sim',
  'Muse of the Maker',
  'Muser',
  'Museum Patron',
  'Music Lover',
  'Natural Leader',
  'Natural Speaker',
  'Naturalist',
  'Neat',
  'Needs No One',
  'Never Weary',
  'Night Owl',
  'Night Wraith',
  'Noncommittal',
  'Observant',
  'Outgoing',
  'Over-Achiever',
  'Paintbrush Revolutionary',
  'Paranoid',
  'Paranormal Investigator',
  'Perfect Host',
  'Perfectionist',
  'Physically Gifted',
  'Picky Eater',
  'Piper',
  'Player',
  'Playful',
  'Poetic',
  'Potion Master',
  'Prepared Voyager',
  'Professional Slacker',
  'Professorial',
  'Proper',
  'Prowler',
  'Quick Learner',
  'Rebellious',
  'Recycle Disciple',
  'Regained Humanity',
  'Responsible',
  'Role Model',
  'Romantic',
  'Sacred Knitting Knowledge',
  'Savant',
  'Scouting Aptitude',
  'Seldom Sleepy',
  'Self-Absorbed',
  'Self-Assured',
  'Shameless',
  'Shrewd',
  'Sickness Resistance',
  'Silly',
  'Sincere',
  'Skittish',
  'Sleight of Hand',
  'Sleuth',
  'Slinger of Spells',
  'Slob',
  'Smart',
  'Snob',
  'Socially Gifted',
  'Spectral Look',
  'Speed Cleaner',
  'Speed Reader',
  'Spice Hound',
  'Spoiled',
  'Squeamish',
  'Steel Bladder',
  'Storm Chaser',
  'Stoves and Grills Master',
  'Strong Bloodline',
  'Stubborn',
  'Sulani Mana',
  'Super Green Thumb',
  'Supreme Authority',
  'Survival Instinct',
  'Survivalist',
  'Talkative',
  'Temporary Genius',
  'Territorial',
  'Thrifty',
  'Top-Notch Toddler',
  'Tormentor',
  'Treasure Hunter',
  'Troublemaker',
  'Uncontrolled Emotions',
  'Unflirty',
  'Unstoppable Fame',
  'Vegetarian',
  'Vicarious',
  'Vocal',
  'Waterproof',
  'Weak Bloodline',
  'Webmaster',
  'Wild',
  'World-Renowned Actor',
  'Worldly Knowledge'
]
